version: "3"

services:
  userprofile-ui-sample:
    container_name: userprofile-ui-sample
    build:
      context: ./userprofile-ui-sample
      dockerfile: ./Dockerfile
    ports:
        - "8080:8080"
    environment:
        - apiUrl=http://localhost:3001
    links:
        - jwt-auth
  jwt-auth:
    container_name: jwt-auth
    build:
      context: ./node-jwt-auth
    ports:
      - "3001:3000"
    environment:
      - DB_CONNECTION_URL=mongodb://mongo:27017
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017

volumes:
  data-volume:
